# values.yaml
appName: "animal-generator3"
# Database configuration
database:
  host: "svc-postgres-headless"
  port: 5432
  name: "postgres-db"
  user: "postgres-db"
  password: "plschangeme"

# Application configuration
application:
  farm: "Farm3"
  table: "bird_locations"
  delay_range: "1-20"
  appName: "animal-generator3"

serviceAccount:
  create: true
  name: ""

#################### Create Service ####################

service:
  type: ClusterIP
  port: 80
# Kubernetes Deployment configuration
image:
  repository: jieshilyn/birds_pg_generator
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
containerPort: 8081
