# values.yaml
appName: "animal-generator"
# Database configuration
database:
  host: "svc-postgres-headless"
  port: 5432
  name: "postgres-db"
  user: "postgres-db"
  password: "plschangeme"

# Application configuration
application:
  farm: "Farm1"
  table: "sheep_locations"
  delay_range: "1-20"
  appName: "animal-generator"

serviceAccount:
  create: true
  name: ""

#################### Create Service ####################

service:
  type: ClusterIP
  port: 80
# Kubernetes Deployment configuration
image:
  repository: jieshilyn/sheeps_pg_generator
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
containerPort: 8080
