{{- if .Values.headlessService }}
apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.appName }}-headless
  labels:
    app: {{ .Values.appName }}
spec:
  type: ClusterIP
  ports:
    - name: rest
      protocol: TCP
      port: {{ .Values.headlessServicePort }}
  clusterIP: None
  selector:
    app: {{ .Values.appName }}
{{- end }}