apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.appName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.appName }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Namespace }}-{{ .Values.appName }}
roleRef:
  kind: ClusterRole
  name: "system:openshift:scc:anyuid"
  apiGroup: rbac.authorization.k8s.io