{{- if (.Values.persistentStorage) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.appName }}-data-{{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
{{- end }}
