{{- if .Values.externalService }}
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: {{ .Values.appName }}-virtual-service
spec:
  hosts:
    - {{ .Values.external.hostName | quote }}
  gateways:
    - istio-ingressgateway
  tcp:
  {{- $fullName := .Values.appName }}
  {{- $brokers := .Values.replicas | int }}
  {{- $root := . }}
  {{- range $i, $e := until $brokers }}
    {{- $externalListenerPort := add $root.Values.external.firstServicePort $i }}
    {{- $responsiblePod := printf "%s-%d" (printf "%s" $fullName) $i }}
    - match:
        - port: {{ $externalListenerPort }}
      route:
        - destination:
            host: svc-{{ $fullName }}-{{ $i }}-external.{{ $root.Release.Namespace }}.svc.cluster.local
            port:
              number: {{ $externalListenerPort }}
  {{- end }}
{{- end }}